<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-02-15 08:05
=======
# Generated by Django 5.1.5 on 2025-02-12 18:18
>>>>>>> 32917af504acf0e0e8023d8f2dc39dd099e0b5d9

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('multiagent', '0001_initial'),
=======
>>>>>>> 32917af504acf0e0e8023d8f2dc39dd099e0b5d9
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_usage_hours', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('web_usage_data', models.JSONField(default=dict)),
                ('number_of_clicks_web', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_clicks', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
<<<<<<< HEAD
                ('multiagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiagent.multiagent')),
=======
>>>>>>> 32917af504acf0e0e8023d8f2dc39dd099e0b5d9
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
