<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-02-15 08:05
=======
# Generated by Django 5.1.5 on 2025-02-14 17:00
>>>>>>> 32917af504acf0e0e8023d8f2dc39dd099e0b5d9

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiAgent',
            fields=[
<<<<<<< HEAD
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(default='Unnamed Model', max_length=255)),
                ('photos', models.JSONField(default=list)),
                ('texts', models.JSONField(default=list)),
                ('videos', models.JSONField(default=list)),
=======
                ('multiAgent_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(default='Unnamed Model', max_length=255)),
                ('photos', models.JSONField(default=list)),
                ('texts', models.JSONField(default=list)),
                ('vid', models.JSONField(default=list)),
>>>>>>> 32917af504acf0e0e8023d8f2dc39dd099e0b5d9
                ('cookies', models.JSONField(default=list)),
                ('web_usage', models.JSONField(default=dict)),
            ],
        ),
    ]
