# Generated by Django 5.1.5 on 2025-02-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiAgent',
            fields=[
                ('multiAgent_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(default='Unnamed Model', max_length=255)),
                ('photos', models.JSONField(default=list)),
                ('texts', models.JSONField(default=list)),
                ('vid', models.JSONField(default=list)),
                ('cookies', models.JSONField(default=list)),
                ('web_usage', models.JSONField(default=dict)),
            ],
        ),
    ]
