# Generated by Django 5.1.5 on 2025-02-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiagent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiagent',
            old_name='vid',
            new_name='videos',
        ),
    ]
