# Generated by Django 5.1.5 on 2025-02-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiagent', '0002_multiagent_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiagent',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='multiagent',
            name='model_id',
        ),
        migrations.AddField(
            model_name='multiagent',
            name='multiAgent_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
