# Generated by Django 5.1.5 on 2025-02-13 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_remove_analysis_multiagent_id_and_more'),
        ('multiagent', '0003_remove_multiagent_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiagent',
            name='model_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis'),
        ),
        migrations.AlterField(
            model_name='multiagent',
            name='multiAgent_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
