# Generated by Django 5.1.5 on 2025-02-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('analyzedPhoto', models.TextField(default='No photo analyzed.')),
                ('analyzedText', models.TextField(default='No text analyzed.')),
                ('analyzedVideo', models.TextField(default='No video analyzed.')),
                ('analyzedWebUsage', models.TextField(default='No web usage analyzed.')),
            ],
        ),
    ]
