# Generated by Django 5.1.5 on 2025-02-14 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysis_reco_id'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='rep_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.report'),
        ),
    ]
