# Generated by Django 5.1.5 on 2025-02-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_remove_analysis_id_analysis_model_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='multiAgent_id',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='model_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
