# Generated by Django 5.1.5 on 2025-02-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_analysis_rep_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='reco_id',
            new_name='reco',
        ),
        migrations.RenameField(
            model_name='analysis',
            old_name='rep_id',
            new_name='rep',
        ),
    ]
