# Generated by Django 5.1.5 on 2025-02-15 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_rename_reco_id_analysis_reco_and_more'),
        ('user', '0005_remove_history_id_alter_history_userhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='userHistory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.history'),
        ),
    ]
