# Generated by Django 5.1.5 on 2025-02-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('recomID', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(default='No description available.')),
                ('category', models.CharField(default='General', max_length=255)),
            ],
        ),
    ]
