# Generated by Django 5.1.5 on 2025-02-12 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed User', max_length=255)),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('gender', models.CharField(default='Not Specified', max_length=10)),
                ('email', models.EmailField(default='example@example.com', max_length=254, unique=True)),
                ('password', models.CharField(default='password123', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
