# Generated by Django 5.1.5 on 2025-02-15 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='userHistory_id',
            new_name='userHistory',
        ),
    ]
