# Generated by Django 5.1.5 on 2025-02-15 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_userhistory_id_history_userhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='id',
        ),
        migrations.AlterField(
            model_name='history',
            name='userHistory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='histories', serialize=False, to='user.customuser'),
        ),
    ]
