# Generated by Django 5.1.5 on 2025-02-15 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_useractivity_images_useractivity_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='session_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
