# Generated by Django 5.1.5 on 2025-02-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_useractivity_session_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='session_time',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
